In [14]:
!pip install pandas openpyxl

import pandas as pd

Requirement already satisfied: pandas in /home/codespace/.local/lib/python3.12/site-packages (2.3.1)
Requirement already satisfied: openpyxl in /usr/local/python/3.12.1/lib/python3.12/site-packages (3.1.5)
Requirement already satisfied: numpy>=1.26.0 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: et-xmlfile in /usr/local/python/3.12.1/lib/python3.12/site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python3 -m pip install --upgrade pip

# Listado de Comercializadoras de electricidad

## Según CNMC

In [15]:
# https://sede.cnmc.gob.es/listado/censo/2
file_path = 'Excels/comercializadoras.xlsx'  

comercializadoras_cnmc_df = pd.read_excel(file_path)

comercializadoras_cnmc_df

,Nº de orden,Nombre empresa,Dirección empresa,C.P.,Municipio empresa,Provincia empresa,Teléfono Att cliente gratuito,Ámbito actuación,NIF empresa,Fecha alta,Fecha baja,Página web,Estado
0,R2-001,ENDESA ENERGÍA S.A.U.,"C/ RIBERA DEL LOIRA, Nº 60",28042,MADRID,Madrid,800 760 909,N; INTER AND,A81948077,NaN,NaN,www.endesaclientes.com,NaN
1,R2-002,"IBERDROLA, S.A.",C/ CARDENAL GARDOQUI 8,48008,BILBAO,Vizcaya,NaN,NaN,A48010615,NaN,23/10/2012,NaN,Baja
2,R2-004,"TOTALENERGIES MERCADO ESPAÑA, S.A.U. (EXTINGUIDA)","PLAZA FERROVIARIOS ASTURIANO, 1",33012,OVIEDO,Asturias,900 907 000,N,A33543547,NaN,02/12/2024,www.totalenergies.es,Baja
3,R2-005,"BASSOLS ENERGIA COMERCIAL, S.L","AVDA. GIRONA, 2",17800,OLOT,Gerona,900 701 169,P; SB; GC; TF; FL; PA; LG; HI,B17653213,NaN,NaN,www.bassolsenergia.com,NaN
4,R2-006,"ELECTRA CALDENSE ENERGIA, S.A.","PLAZA DE CATALUÑA, 3, 1º",08140,CALDES DE MONTBUI,Barcelona,900 181 776,N,A62420815,NaN,NaN,www.electracaldense.com,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
874,R2-995,REPRESENTANTES DE CONSUMIDORES EN EL MERCADO E...,"CALLE LEGAZ 5, BAJO",30850,TOTANA,MURCIA,900 909 137,P,B73861908,09/10/2023,NaN,www.emececuadrado.com,NaN
875,R2-996,"SECOND FOUNDATION ENERGY, A.S.","Klimentská 1216/46, 110 00 Praga 1 Nove Mesto",NaN,NaN,REPÚBLICA CHECA,900 525 512,P,CZ14160218,15/12/2022,NaN,https://www.second-foundation.eu/,NaN
876,R2-997,"CENTRAL HIDROELECTRICA SAN PEDRO DE ARAIA, S.A.","HERRIKO ENPARANTZA, 1",01250,ASPARRENA,ARABA/ÁLAVA,900 102 119,P,A01323310,20/06/2023,NaN,www.centralaraia.com,NaN
877,R2-998,"FRANK ENERGIA IBERIA, S.L.","RONDA DE SANT PERE, NUM 17",08010,BARCELONA,BARCELONA,900 732 949,P,B13936968,22/11/2023,NaN,https://www.frankenergia.es/es,NaN
878,R2-999,"MAXI ENERGIA Y CONSULTORES, S.L.","RONDA DE SANT PERE, 54 BJ",08010,BARCELONA,BARCELONA,900 831 210,P,B44953636,05/09/2023,NaN,https://www.maxienergia.es/,NaN

Muestra las comercializadoras no tengan fecha de baja

In [16]:
comercializadoras_cnmc_vigentes_df = comercializadoras_cnmc_df[comercializadoras_cnmc_df['Fecha baja'].isna()]

comercializadoras_cnmc_vigentes_df

,Nº de orden,Nombre empresa,Dirección empresa,C.P.,Municipio empresa,Provincia empresa,Teléfono Att cliente gratuito,Ámbito actuación,NIF empresa,Fecha alta,Fecha baja,Página web,Estado
0,R2-001,ENDESA ENERGÍA S.A.U.,"C/ RIBERA DEL LOIRA, Nº 60",28042,MADRID,Madrid,800 760 909,N; INTER AND,A81948077,NaN,NaN,www.endesaclientes.com,NaN
3,R2-005,"BASSOLS ENERGIA COMERCIAL, S.L","AVDA. GIRONA, 2",17800,OLOT,Gerona,900 701 169,P; SB; GC; TF; FL; PA; LG; HI,B17653213,NaN,NaN,www.bassolsenergia.com,NaN
4,R2-006,"ELECTRA CALDENSE ENERGIA, S.A.","PLAZA DE CATALUÑA, 3, 1º",08140,CALDES DE MONTBUI,Barcelona,900 181 776,N,A62420815,NaN,NaN,www.electracaldense.com,NaN
5,R2-008,"ELECTRA DEL CARDENER ENERGIA, S.A.","PASEO DE LAS MORERAS, S/N",25280,SOLSONA,Lérida,900 102 261,P,A25466939,NaN,NaN,www.ecardener.com,NaN
6,R2-009,"ELECTRA ENERGIA, S.A.","C/ XIMENEZ, 15",12002,CASTELLÓN,Castellón,900 373 275 900 373 285,P,A12542296,NaN,NaN,www.electraenergia.es,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
874,R2-995,REPRESENTANTES DE CONSUMIDORES EN EL MERCADO E...,"CALLE LEGAZ 5, BAJO",30850,TOTANA,MURCIA,900 909 137,P,B73861908,09/10/2023,NaN,www.emececuadrado.com,NaN
875,R2-996,"SECOND FOUNDATION ENERGY, A.S.","Klimentská 1216/46, 110 00 Praga 1 Nove Mesto",NaN,NaN,REPÚBLICA CHECA,900 525 512,P,CZ14160218,15/12/2022,NaN,https://www.second-foundation.eu/,NaN
876,R2-997,"CENTRAL HIDROELECTRICA SAN PEDRO DE ARAIA, S.A.","HERRIKO ENPARANTZA, 1",01250,ASPARRENA,ARABA/ÁLAVA,900 102 119,P,A01323310,20/06/2023,NaN,www.centralaraia.com,NaN
877,R2-998,"FRANK ENERGIA IBERIA, S.L.","RONDA DE SANT PERE, NUM 17",08010,BARCELONA,BARCELONA,900 732 949,P,B13936968,22/11/2023,NaN,https://www.frankenergia.es/es,NaN
878,R2-999,"MAXI ENERGIA Y CONSULTORES, S.L.","RONDA DE SANT PERE, 54 BJ",08010,BARCELONA,BARCELONA,900 831 210,P,B44953636,05/09/2023,NaN,https://www.maxienergia.es/,NaN

## Listado de Comercializadoras de referencia de electricidad

In [17]:
# https://sede.cnmc.gob.es/listado/censo/16

## Según REE

In [18]:
# https://www.esios.ree.es/es/descargas
file_path = 'Excels/121-Comercializadores.xlsx'  

comercializadoras_ree_df = pd.read_excel(file_path)

comercializadoras_ree_df

     Código                  Empresa   Unidad           Fecha Alta   Estado
0       816                      816  LUMIC01  2012-07-07 00:00:00  VIGENTE
1      1337                     1337  DUFEC01  2018-12-18 00:00:00  VIGENTE
2      1624       3D SMART ENERGY SL  DSMAC01  2021-12-08 00:00:00  VIGENTE
3      1670  A&R INTERXAT IBERICA SL  VDLUC01  2022-05-04 00:00:00  VIGENTE
4      1850         A2J ENERGIA, S.L  AJENC01  2024-10-03 00:00:00  VIGENTE
...     ...                      ...      ...                  ...      ...
2480   1841  ZETA ENERXIA GALEGA S.L  ZETAELG  2024-08-03 00:00:00  VIGENTE
2481   1841  ZETA ENERXIA GALEGA S.L  ZETAEPA  2024-08-03 00:00:00  VIGENTE
2482   1841  ZETA ENERXIA GALEGA S.L  ZETAETF  2024-08-03 00:00:00  VIGENTE
2483   1841  ZETA ENERXIA GALEGA S.L  ZETAC01  2024-08-10 00:00:00  VIGENTE
2484   1681            ZUG POWER, SL  ZUGPC01  2022-06-14 00:00:00  VIGENTE

[2485 rows x 5 columns]

Muestra las comercializadoras que tengan códigos distintos

In [19]:
comercializadoras_ree_unicos_df =  comercializadoras_ree_df.drop_duplicates(subset=['Empresa'])

comercializadoras_ree_unicos_df = comercializadoras_ree_unicos_df.dropna(subset=['Empresa'])

comercializadoras_ree_unicos_df

,Código,Empresa,Unidad,Fecha Alta,Estado
0,816,816,LUMIC01,2012-07-07 00:00:00,VIGENTE
1,1337,1337,DUFEC01,2018-12-18 00:00:00,VIGENTE
2,1624,3D SMART ENERGY SL,DSMAC01,2021-12-08 00:00:00,VIGENTE
3,1670,A&R INTERXAT IBERICA SL,VDLUC01,2022-05-04 00:00:00,VIGENTE
4,1850,"A2J ENERGIA, S.L",AJENC01,2024-10-03 00:00:00,VIGENTE
...,...,...,...,...,...
2472,852,"XENERA COMPAÑÍA ELÉCTRICA, S.A.",GEGC01,2013-03-20 00:00:00,VIGENTE
2474,1827,"YOU ARE ENERGY, S.L",YOURC01,2024-06-01 00:00:00,VIGENTE
2475,777,ZELTRIA ENERGIA,ZELTC01,2011-11-25 00:00:00,VIGENTE
2476,1841,ZETA ENERXIA GALEGA S.L,ZETASB,2024-07-30 00:00:00,VIGENTE
2484,1681,"ZUG POWER, SL",ZUGPC01,2022-06-14 00:00:00,VIGENTE

Comparar ambas listas

In [20]:
empresas_cnmc = comercializadoras_cnmc_vigentes_df['Nombre empresa'].dropna().str.strip().unique()  
empresas_ree = comercializadoras_ree_unicos_df['Empresa'].dropna().str.strip().unique()  

# Convert to sets for efficient comparison
set_cnmc = set(empresas_cnmc)
set_ree = set(empresas_ree)

common_values = set_cnmc.intersection(set_ree)  # Same values in both
missing_in_cnmc = set_ree.difference(set_cnmc)  
missing_in_ree = set_cnmc.difference(set_ree)  

print("Número total de valores en el listado de REE:", len(set_ree))
print("Número total de valores en el listado de la CNMC:", len(set_cnmc))
print("\nNúmero de valores comunes:", len(common_values))

Número total de valores en el listado de REE: 614
Número total de valores en el listado de la CNMC: 557

Número de valores comunes: 84

In [21]:
print("\nValores que están en el listado de la CNMC, pero no en el de REE:")

df_falta_en_REE = comercializadoras_cnmc_vigentes_df[comercializadoras_cnmc_vigentes_df['Nombre empresa'].isin(missing_in_ree)]
df_falta_en_REE.style.hide(axis='index')

Valores que están en el listado de la CNMC, pero no en el de REE:

In [22]:
print("\nValores que están en el listado de REE, pero no en el de la CNMC:")

df_falta_en_CNMC = comercializadoras_ree_unicos_df[comercializadoras_ree_unicos_df['Empresa'].isin(missing_in_cnmc)]
df_falta_en_CNMC.style.hide(axis='index')

Valores que están en el listado de REE, pero no en el de la CNMC: